# fly.toml file generated for riemann on 2022-05-26T21:37:27+07:00

app = "riemann"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  PORT = "8000"
  DJANGO_ALLOWED_HOSTS="riemann.fly.dev"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[[statics]]
  guest_path = "/venv/lib/python3.10/site-packages/staticfiles"
  url_prefix = "/static/"
